### ISSUE TITLE
Invalid exchange code in database

### ISSUE THREAD

**Issue by dnwz99-wang** [azerothcore/mod-reward-shop#21]
The exchange code created by GM mode is %s in the Database, The self added exchange code in the Database cannot be recognized.
After the exchange, the status is not changed and an error is reported...

UPDATE reward_shop SET status = 1, PlayerGUID = '%u', PlayerIP = '%s' WHERE code = '%s'

[1366] Incorrect integer value: '%u' for column 'PlayerGUID' at row 1
Unhandled MySQL errno 1366. Unexpected behaviour possible.

**Comment by lovepush** [comment]
You can use {} to replace '%u' and '%s'

**Comment by 0xCiBeR** [comment]
PR #24 should fix this. :)

**Comment by Helias** [comment]
thank you!
