### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by icecatbing** [azerothcore/mod-reward-shop#4]
Error in compilation

Can someone help me out, ty.

Here are some useful information:

AzerothCore rev. 2eb070566807+ 2020-02-28 17:02:54 +0100 (master branch) (Unix, Release)

Included mod

mod-cfbg   build passing
mod-character-tools   build passing
mod-transmog  build passing
mod-reward-shop  **build error**

`/root/azerothcore/modules/mod-reward-shop/src/reward_shop.cpp:51:68: fatal error: unused parameter 'sender' [-Wunused-parameter]
/root/azerothcore/modules/mod-reward-shop/src/reward_shop.cpp:127:24: fatal error: unused variable 'id' [-Wunused-variable]`

**Comment by BarbzYHOOL** [comment]
remove the unused parameters from the code (from the functions arguments), linux compilers are stricter

**Comment by Helias** [comment]
Fixed by https://github.com/azerothcore/mod-reward-shop/commit/65f719d0c6596b7f67ae191b8682d8c8d5565ba1
